
.autenticate()
            --> then -> caso o promise deu certo
promise --|
            --> catch -> caso o promise deu um erro, para tratar esse erro


ex: authenticate().then({

}).catch((erro) => {})